name: CI/CD Pipeline

# Definindo em quais eventos o workflow será acionado.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Faz o checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v2

    # Instala Node.js e configura a versão necessária
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Instala as dependências
    - name: Install dependencies
      run: npm install

    # Compila o TypeScript para verificar se o código está correto
    - name: Compile TypeScript
      run: npm run build
